# Generated by Django 4.2.4 on 2023-10-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectcategory', models.CharField(blank=True, max_length=50, null=True)),
                ('jobtype', models.IntegerField(blank=True, max_length=50, null=True)),
                ('selectlocation', models.CharField(blank=True, max_length=50, null=True)),
                ('experiance', models.IntegerField(blank=True, max_length=50, null=True)),
                ('jobimg', models.ImageField(blank=True, null=True, upload_to='category')),
            ],
        ),
    ]
