# Generated by Django 4.2.4 on 2023-11-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydb',
            name='comdes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='categorydb',
            name='comemail',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='categorydb',
            name='comname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='categorydb',
            name='comwebsite',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='categorydb',
            name='jobdes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='categorydb',
            name='qualif',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='categorydb',
            name='skills',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='experiance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='jobtype',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
