# Generated by Django 4.2.4 on 2023-11-29 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0002_categorydb_comdes_categorydb_comemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydb',
            name='posted_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
