# Generated by Django 4.2.4 on 2023-11-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0003_categorydb_posted_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='posted_time',
            new_name='posted_datetime',
        ),
    ]
