# Generated by Django 4.2.4 on 2023-11-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0004_rename_posted_time_categorydb_posted_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='posted_datetime',
            new_name='posted_time',
        ),
    ]
