# Generated by Django 4.2.4 on 2023-12-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0005_rename_posted_datetime_categorydb_posted_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comname', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('descrip', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='categorydb',
            name='comdes',
        ),
        migrations.RemoveField(
            model_name='categorydb',
            name='comemail',
        ),
        migrations.RemoveField(
            model_name='categorydb',
            name='comname',
        ),
        migrations.RemoveField(
            model_name='categorydb',
            name='comwebsite',
        ),
        migrations.RemoveField(
            model_name='categorydb',
            name='posted_time',
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='jobdes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='qualif',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='skills',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
