# Generated by Django 5.0 on 2024-01-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0007_rename_city_companydb_companyname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydb',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
