# Generated by Django 5.0.1 on 2024-01-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0008_companydb_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='experiance',
            new_name='jobexperience',
        ),
        migrations.RenameField(
            model_name='categorydb',
            old_name='qualif',
            new_name='jobname',
        ),
        migrations.RenameField(
            model_name='categorydb',
            old_name='selectcategory',
            new_name='lpa',
        ),
        migrations.RenameField(
            model_name='categorydb',
            old_name='selectlocation',
            new_name='qualification',
        ),
        migrations.RemoveField(
            model_name='categorydb',
            name='jobimg',
        ),
        migrations.AddField(
            model_name='categorydb',
            name='joblocation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='jobtype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
