# Generated by Django 5.0.1 on 2024-01-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0011_categorydb_comapnyname_categorydb_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='company_id',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
