# Generated by Django 5.0.1 on 2024-01-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0013_alter_categorydb_comapnyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='comapnyname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='company_id',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
