# Generated by Django 5.0.1 on 2024-01-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0015_categorydb_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydb',
            name='posted',
            field=models.DateField(auto_now=True),
        ),
    ]
