# Generated by Django 5.0.1 on 2024-01-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0016_categorydb_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
