# Generated by Django 5.0.1 on 2024-01-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0017_alter_categorydb_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydb',
            name='profile',
        ),
    ]
