# Generated by Django 5.0.1 on 2024-01-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0018_remove_categorydb_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydb',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
