# Generated by Django 5.0.1 on 2024-01-24 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0019_categorydb_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend1.companydb'),
        ),
    ]
