# Generated by Django 5.0.1 on 2024-01-24 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0020_alter_categorydb_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend1.companydb'),
            preserve_default=False,
        ),
    ]
