# Generated by Django 5.0.1 on 2024-01-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0022_alter_categorydb_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='cart'),
        ),
    ]
