# Generated by Django 4.2.4 on 2023-11-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdb',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
