# Generated by Django 5.0.1 on 2024-01-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_registerdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdb',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registerdb',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
