# Generated by Django 5.0.1 on 2024-01-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_registerdb_mobile_registerdb_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdb',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
