# Generated by Django 5.0.1 on 2024-01-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_registerdb_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdb',
            name='address',
            field=models.CharField(blank=True, default='Update Address', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registerdb',
            name='age',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='registerdb',
            name='dob',
            field=models.CharField(blank=True, default='Update Date Of Birth', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registerdb',
            name='sex',
            field=models.CharField(blank=True, default='Update sex', max_length=20, null=True),
        ),
    ]
