# Generated by Django 5.0.1 on 2024-01-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_applicationdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdb',
            name='reply',
            field=models.CharField(blank=True, default='No Reply', max_length=500, null=True),
        ),
    ]
