# Generated by Django 4.2.4 on 2023-12-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_resume'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resume',
            new_name='ResumeDb',
        ),
    ]
