# Generated by Django 4.2.4 on 2023-12-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0004_delete_resumedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdb',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes'),
        ),
    ]
